src/Entity/Gallery.php
<?php

namespace App\Entity;

use App\Repository\GalleryRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GalleryRepository::class)]
class Gallery
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $filename = null;

    #[ORM\Column(length: 255)]
    private ?string $filepath = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $create_date = null;

    #[ORM\Column]
    private ?bool $profile = null;

    #[ORM\ManyToOne(inversedBy: 'gallery')]
    #[ORM\JoinColumn(nullable: false)]
    private ?UserParams $user_params = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getFilepath(): ?string
    {
        return $this->filepath;
    }

    public function setFilepath(string $filepath): self
    {
        $this->filepath = $filepath;

        return $this;
    }

    public function getCreateDate(): ?\DateTimeInterface
    {
        return $this->create_date;
    }

    public function setCreateDate(\DateTimeInterface $create_date): self
    {
        $this->create_date = $create_date;

        return $this;
    }

    public function isProfile(): ?bool
    {
        return $this->profile;
    }

    public function setProfile(bool $profile): self
    {
        $this->profile = $profile;

        return $this;
    }

    public function getUserParams(): ?UserParams
    {
        return $this->user_params;
    }

    public function setUserParams(?UserParams $user_params): self
    {
        $this->user_params = $user_params;

        return $this;
    }
}

src/Controller/ProfileMainController.php
<?php

namespace App\Controller;

use \Datetime;
use App\Entity\User;
use App\Entity\UserParams;
use App\Entity\Gallery;
use App\Form\ProfileFillForm;
use App\Form\ProfileRemoveForm;
use App\Form\ProfileEdit\EditFirstnameForm;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Doctrine\Persistence\ManagerRegistry;

class ProfileMainController extends AbstractController
{
    #[Route('/Profil', name: 'app_profile_main')]
    public function profileMain(Request $request, ManagerRegistry $doctrine): Response
    {   

        if($this->getUser()->getUserParams() === null) {

            return $this->redirectToRoute('app_profile_main_make');

        } else {

            $user = $this->getUser();
            $userParams = $this->getUser()->getUserParams();

            $profileRemoveForm = $this->createForm(ProfileRemoveForm::class);
            $profileRemoveForm->handleRequest($request);

            if($profileRemoveForm->isSubmitted()) {
                return $this->redirectToRoute('app_profile_main_remove');
            }

            $em = $doctrine->getManager();

            $editFirstnameForm = $this->createForm(EditFirstnameForm::class);
            $editFirstnameForm->handleRequest($request);

            if($editFirstnameForm->isSubmitted()) {

                $data = $editFirstnameForm->getData();

                $userParams->setFirstname($data['firstname']);
                $em->flush();
            }

            return $this->renderForm('ProfileMain/profile_main.html.twig', [
                'profileRemoveForm' => $profileRemoveForm,
                'editFirstnameForm' => $editFirstnameForm,
                'user' => $user,
                'userParams' => $userParams,
            ]);
        }
    }

    #[Route('/Profil/Utwórz', name: 'app_profile_main_make')]
    public function profileMainMake(Request $request): Response
    {  
        $userParams = new UserParams();
        
        $makeProfileForm = $this->createFormBuilder()
            ->add('fillProfile', SubmitType::class, ['label' => 'Utwórz Profil'])
            ->getForm();

        $makeProfileForm->handleRequest($request);

        if($makeProfileForm->isSubmitted()) {
            
            return $this->redirectToRoute('app_profile_main_fill');
        }

        return $this->renderForm('ProfileMain/profile_main_make.html.twig', [
            'makeProfileForm' => $makeProfileForm,
        ]);
    }

    #[Route('/Profil/Wypełnij', name: 'app_profile_main_fill')]
    public function profileMainFill(Request $request, ManagerRegistry $doctrine): Response
    {  

        $userParams = new UserParams();

        $profileFillForm = $this->createForm(ProfileFillForm::class, $userParams);
        $profileFillForm->handleRequest($request);

        if($profileFillForm->isSubmitted()) {

            $userParams = $profileFillForm->getData();

            $em = $doctrine->getManager();
            $em->persist($userParams);
            $em->flush();

            $user = $this->getUser();
            $user->setUserParams($userParams);
            $em->flush();

            return $this->redirectToRoute('app_profile_main');

        } else {

            $userParams = $this->getUser()->getUserParams();
            
            $profileFillForm = $this->createForm(ProfileFillForm::class, $userParams);
            $profileFillForm->handleRequest($request);
        }

        return $this->renderForm('ProfileMain/profile_main_fill.html.twig', [
            'profileFillForm' => $profileFillForm,
        ]);
    }

    #[Route('/Profil/Usuń', name: 'app_profile_main_remove')]
    public function profileMainRemove(Request $request, ManagerRegistry $doctrine): Response
    {  

        $user = $this->getUser();
        $userParams = $user->getUserParams();

        $user->setUserParams(null);

        $em = $doctrine->getManager();
        $em->flush();

        $em->remove($userParams);
        $em->flush();

        return $this->redirectToRoute('app_home');
    }

    #[Route('/Profil/Test', name: 'app_profile_main_test')]
    public function profileMainTest(Request $request, ManagerRegistry $doctrine): Response
    {  

        $em = $doctrine->getManager();

        $userParams = $this->getUser()->getUserParams();
        
        $userParams->setSex($_POST['sex']);
        $userParams->setFirstname($_POST['firstname']);
        $userParams->setLastname($_POST['lastname']);
        $em->flush();

        return new Response("NO SIEMANO");
    }

    #[Route('/Profil/UploadImage', name: 'app_profile_main_upload_image')]
    public function profileUploadImage(Request $request, ManagerRegistry $doctrine): Response
    {  

        $data = $request->get('image');
        echo $data;


        if(isset($_FILES['image'])) {
            $fileName = $_FILES['image']['name'];
            $fileTmp = $_FILES['image']['tmp_name'];
        }

        $projectRoot = $this->getParameter('kernel.project_dir');
        $move = "/gallery/26/";
        
        $path = $projectRoot.$move.$fileName;

        echo $projectRoot;

        // echo $webPath;
        echo "\n";
        echo $fileName;
        echo "\n";
        echo $fileTmp;

        echo "\n";
        echo "\n";
        echo "\n";
        

        move_uploaded_file($fileTmp, $path);

        // return new Response(implode(",", $_FILES['image']));
        return new Response($data);
    }

    #[Route('/Profil/Galeria', name: 'app_profile_main_gallery')]
    public function profileGallery(Request $request, ManagerRegistry $doctrine): Response
    {  

        $user = $this->getUser();
        $userParams = $this->getUser()->getUserParams();

        $em = $doctrine->getManager();

        if(isset($_FILES['image_profile'])) {

            $countPhotos = count($_FILES['image_profile']['name']);

            for($i = 0; $i < $countPhotos; $i++) {

                $filename = $_FILES['image_profile']['name'][$i];
                $ext = pathinfo($filename)['extension'];

                $filename = substr(md5(uniqid(mt_rand(), true)), 0, 10) . '.' . $ext;
                $fileTmp = $_FILES['image_profile']['tmp_name'][$i];
                $dirRelative = '/gallery/' . $user->getId() . '/' . $filename;
                $dirPhoto = $this->getParameter('kernel.project_dir') . '/public' . $dirRelative;

                move_uploaded_file($fileTmp, $dirPhoto);

                $photo = new Gallery();
                $photo->setUserParams($userParams);
                $photo->setFilename($filename);
                $photo->setFilepath($dirRelative);
                $photo->setCreateDate(new DateTime());
                $photo->setProfile(true);

                $em->persist($photo);
                $em->flush();
            }
        }

        if(isset($_FILES['image_photos'])) {

            $countPhotos = count($_FILES['image_photos']['name']);

            for($i = 0; $i < $countPhotos; $i++) {

                $filename = $_FILES['image_photos']['name'][$i];
                $ext = pathinfo($filename)['extension'];

                $filename = substr(md5(uniqid(mt_rand(), true)), 0, 10) . '.' . $ext;
                $fileTmp = $_FILES['image_photos']['tmp_name'][$i];
                $dirRelative = '/gallery/' . $user->getId() . '/' . $filename;
                $dirPhoto = $this->getParameter('kernel.project_dir') . '/public' . $dirRelative;

                move_uploaded_file($fileTmp, $dirPhoto);

                $photo = new Gallery();
                $photo->setUserParams($userParams);
                $photo->setFilename($filename);
                $photo->setFilepath($dirRelative);
                $photo->setCreateDate(new DateTime());
                $photo->setProfile(false);

                $em->persist($photo);
                $em->flush();
            }
        }

        $galleryProfile = $em->getRepository(Gallery::class)->findBy([
            'user_params' => $userParams,
            'profile' => (string)true,
        ]);

        $galleryPhotos = $em->getRepository(Gallery::class)->findBy([
            'user_params' => $userParams,
            'profile' => (string)false,
        ]);

        return $this->renderForm('ProfileMain/profile_main_gallery.html.twig', [
            'user' => $user,
            'userParams' => $userParams,
            'galleryProfile' => $galleryProfile,
            'galleryPhotos' => $galleryPhotos,
        ]);
    }
}

templates/ProfileMain/profile_main.html.twig
<!DOCTYPE html>
<html>

<head>

    {% block stylesheets %}
        {{ encore_entry_link_tags('profileMain') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('profileMain') }}
    {% endblock %}

    <script src="https://kit.fontawesome.com/d69551549e.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"> 

    <title>Dater</title>

</head>

<body>
    
    <header>
        <div id="header">
            <a href="{{ path('app_home') }}">Strona główna</a>
            {# <h2>Profil: {{ user.nick }}</h2>
            <hr> #}
        </div>
    </header>
    
    <div id="errors">

    </div>

    <div id="content">

        <div id="content-left">
            <div id="profile-photo">
                <img src=" {{ asset('build/images/profilePhoto.b8428432.svg') }}">
            </div>
            <div>
                <form action="{{ path('app_profile_main_upload_image')}}" method="POST" enctype="multipart/form-data">
                    <div>
                        <input type="file" name="image"/>
                    </div>
                    <div>
                        <input type="submit"/>
                    </div>
                </form>
            </div>
            <div>
                <a href="{{ path('app_profile_main_gallery') }}">GALERIA</a>
            </div>
        </div>

        <div id="content-right">

            <div class="content-right-grid">

                {# 1 IMIE
                2 Nazwisko
                3 płeć
                4 wiek
                5 miejscowość
                6 Stan (single, married)
                7 dzieci
                8 nałogi
                9 zainteresowania
                10 opis #}
                <div id="edit-firstname" class="modal">
                    <div class="modal-content">
                        {{ form(editFirstnameForm) }}
                    </div>
                </div>

                <div class="col-headers row-first"></div>
                <div class="row-first"><h3 style="color: #EE4266">{{ user.nick }}</h3></div>
                <div class="row-first"><h3>Edytuj</h3></div>
                <div class="row-first"><h3>Pokaż</h3></div>

                <div class="col-headers row-grid"><h4>Imię:</h4></div>
                <div class="row-grid"><h4>{{ userParams.firstname }}</h4></div>
                <div class="row-grid"><i id="edit-firstname-icon" class="fa-solid fa-pen-to-square icon-editable"></i></div>
                <div class="row-grid"><i class="fa-solid fa-eye"></i></div>

                <div class="col-headers row-grid"><h4>Nazwisko: </h4></div>
                <div class="row-grid"><h4>{{ userParams.lastname }}</h4></div>
                <div class="row-grid"><i class="fa-solid fa-pen-to-square icon-editable"></i></div>
                <div class="row-grid"><i class="fa-solid fa-eye"></i></div>

                <div class="col-headers row-grid"><h4>Płeć: </h4></div>
                <div class="row-grid"><h4>{{ userParams.sex }}</h4></div>
                <div class="row-grid"><i class="fa-solid fa-pen-to-square icon-editable"></i></div>
                <div class="row-grid"><i class="fa-solid fa-eye"></i></div>

                <div class="col-headers row-grid"><h4>Wiek:</h4></div>
                <div class="row-grid"><h4>{{ userParams.sex }}</h4></div>
                <div class="row-grid"><i class="fa-solid fa-pen-to-square icon-noneditable"></i></div>
                <div class="row-grid"><i class="fa-solid fa-eye"></i></div>

                <div class="col-headers row-grid"><h4>Miejscowość:</h4></div>
                <div class="row-grid"><h4>{{ userParams.sex }}</h4></div>
                <div class="row-grid"><i class="fa-solid fa-pen-to-square icon-editable"></i></div>
                <div class="row-grid"><i class="fa-solid fa-eye"></i></div>

                <div class="col-headers row-grid"><h4>Kraj:</h4></div>
                <div class="row-grid"><h4>{{ userParams.sex }}</h4></div>
                <div class="row-grid"><i class="fa-solid fa-pen-to-square icon-editable"></i></div>
                <div class="row-grid"><i class="fa-solid fa-eye"></i></div>


            </div>




            {# <div id="user-params">

                {% if userParams.sex == 'M' %}
                {% set sexShort = 'Mężczyzna' %}
                {% endif %}
                
                {% if userParams.sex == 'F' %}
                {% set sexShort = 'Kobieta' %}
                {% endif %}
                
                <div id="prop-sex">
                    <div>
                        <i class="fa-solid fa-pen-to-square edit-icon" id="edit-sex-button"></i>
                        <label for="_sex">Płeć</label>
                    </div>

                    <div>
                        <input type="text" id="_sex" value="{{ sexShort }}" autocomplete="off" readonly>
                        <select id="sex-select">
                            <option value="M">Mężczyzna</option>
                            <option value="F">Kobieta</option>
                        </select>
                        <i class="fa-regular fa-circle-check confirm" id="confirm-sex-button"></i>
                    </div>
                </div>

                <div>
                    <div id="prop-firstname">
                        <i class="fa-solid fa-pen-to-square edit-icon" id="edit-firstname-button"></i>
                        <label for="_firstname">Imię</label>
                        <input type="text" id="_firstname" value="{{ userParams.firstname }}" autocomplete="off" readonly>
                        <i class="fa-regular fa-circle-check confirm" id="confirm-firstname-button"></i>
                    </div>

                    <div id="lastname">
                        <i class="fa-solid fa-pen-to-square edit-icon"></i>
                        <label for="_lastname">Nazwisko</label>
                        <input type="text" id="_lastname" value="{{ userParams.lastname }}" autocomplete="off" readonly>
                    </div>
                </div>

            </div> #}

        </div>

    </div>

    <hr>

    <button id="confirm-changes">ZMIEN</button>

    <hr>

    <div>
        <form></form>

    </div>


</body>

</html>

templates/ProfileMain/profile_main_fill.html.twig
<!DOCTYPE html>
<html>

<head>

    

    <title>Dater</title>

</head>

<body>
   
    <a href="{{ path('app_home') }}">Powrót do strony głównej</a>
    <hr>
    {{ form(profileFillForm) }}
    
</body>

</html>

templates/ProfileMain/profile_main_gallery.html.twig
<!DOCTYPE html>
<html>

<head>

    {% block stylesheets %}
        {{ encore_entry_link_tags('profileMainGallery') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('profileMainGallery') }}
    {% endblock %}

    <script src="https://kit.fontawesome.com/d69551549e.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"> 

    <title>Dater</title>

</head>

<body>
    
    <div>

        <header class="header">
            <a href="{{ path('app_home') }}">Strona główna</a>
            <h2>Profil: {{ user.nick }}</h2>
        </header>
        
        <div id="gallery-profile-container">
            
            <div id="gallery-profile-header">
                <div>
                    <h1>ZDJĘCIA PROFILOWE</h1>
                </div>
                <div>
                    <form action="{{ path('app_profile_main_gallery')}}" method="POST" enctype="multipart/form-data">
                        <input type="file" name="image_profile[]" multiple/>
                        <input type="submit" value="Załaduj zdjęcie"/>
                    </form>
                </div>
            </div>
            
            <div id="gallery-profile">
                {% for photo in galleryProfile %}
                <div id="gallery-profile-img-container">
                    <img src={{ photo.filepath }}>
                    <div>
                        <div class="photo-description">
                            <h3>{{ photo.filename }}</h3>
                            <h5>dodano {{ photo.createDate | date('Y-m-d') }}</h5>
                        </div>
                        <div>USUN</div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>

        <div>
            <h1>ZDJĘCIA ZWYKŁE</h1>

            <form action="{{ path('app_profile_main_gallery')}}" method="POST" enctype="multipart/form-data">
                <input type="file" name="image_photos[]"/>
                <input type="submit"/>
                </div>
            </form>

            <div id="gallery-photos">
                {% for photo in galleryPhotos %}
                <img src={{ photo.filepath }}>
                {% endfor %}
            </div>

        </div>        
    </div>

</body>

</html>

templates/ProfileMain/profile_main_make.html.twig
<!DOCTYPE html>
<html>

<head>

    {% block stylesheets %}
        {{ encore_entry_link_tags('profileMain') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('profileMain') }}
    {% endblock %}

    <title>Dater</title>

</head>

<body>
   
    {% for message in app.flashes('clearProfile') %}
        <div class="flash-notice">
            {{ message }}
        </div>
    {% endfor %}

    <a href="{{ path('app_home') }}">Strona główna</a>

    <h1>PROFIL NIE UZUPELNIONY !</h1>
    <h2>Możesz jedynie przegladac inne profile</h2>
    <h2>Żeby uzupelnic swoj profil, kliknij ponizsyz link</h2>
   
    <hr>

    {{ form(makeProfileForm) }}
    
</body>

</html>